language: node_js
node_js:
  - "12"
services:
  - docker

before_install:

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sgt/newisland-test:latest .
  - docker push sgt/newisland-test:latest