module.exports = {
  environment:'dev',
  database:{
    dbName:'fvcksql',
    user:'root',
    password:'admin123',
    host:'localhost',
    port:3306,
  },
  security:{
    secretKey:'aksjf023hfahfc',
    expiresIn:60*60*24*7
  },
  wx:{
    appId:'wx0e3b95d18afb3639',
    appSecret:'5de08fc7673cba3a355a868520ac86e3',
    loginUrl:'https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code'
  },
  yushu:{
    detailUrl:'http://t.yushu.im/v2/book/id/%s',
    keywordUrl:'http://t.yushu.im/v2/book/search?q=%s&start=%s&count=%s&summary=%s',
  },
  host:'http://localhost:3000/'
}